Array0 <- function(x) x |> struct(c('Array0', 'Array0', 'any', 'Empty0'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'any', 'Empty0'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'any', 'Empty0'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'any', 'Empty0'))
Empty0 <- function(x) x |> struct(c('Empty0', 'Empty0', 'any'))
Function4 <- function(x) x |> struct(c('Function4', 'Function4', 'Empty0', 'any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'any', 'Empty0'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'any', 'Empty0'))
Function0 <- function(x) x |> struct(c('Function0', 'Function0', 'Empty0', 'any'))
Generic <- function(x) x |> struct(c('Generic', 'Generic', 'Empty0', 'any'))
Function5 <- function(x) x |> struct(c('Function5', 'Function5', 'any', 'Empty0'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'any', 'Empty0'))
Character <- function(x) x |> struct(c('Character', 'character', 'any', 'Empty0'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'any', 'Empty0'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'any', 'Empty0'))